spring.datasource.url=jdbc:mysql://localhost:3306/adota
spring.datasource.username=root
spring.datasource.password=1201

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true